using System;
using System.Collections.Generic;
using System.Text;

namespace CodeScenes.Analyzers
{
    /// <summary>
    /// b5-t1: manifest JSON (Assets.sbassets.json / AssetCatalog shape) -> typed asset-catalog
    /// source (a static `Assets` class with per-group nested folder classes and one
    /// SceneBuilder.Authoring.AssetReference-typed property per entry). See
    /// .agent_handoffs/typed-asset-catalogs/b5-t1/research.md "Blueprint" for the full contract.
    /// </summary>
    internal static class AssetCatalogEmit
    {
        public static bool TryEmitAssets(string? json, out string source)
        {
            source = "";

            if (string.IsNullOrWhiteSpace(json))
                return false;

            var root = new TrieNode();

            try
            {
                var parsed = CatalogEmit.MiniJson.Parse(json!);
                if (parsed is not Dictionary<string, object?> obj)
                    return false;

                if (!obj.TryGetValue("entries", out var entriesVal) || entriesVal is not List<object?> entriesList)
                    return false;

                if (entriesList.Count == 0)
                    return false;

                foreach (var e in entriesList)
                {
                    if (e is not Dictionary<string, object?> entryObj)
                        return false;

                    if (!entryObj.TryGetValue("group", out var groupVal) || groupVal is not string group)
                        return false;

                    if (!entryObj.TryGetValue("memberName", out var memberVal) || memberVal is not string memberName)
                        return false;

                    var folderSegments = new List<string>();
                    if (entryObj.TryGetValue("folderSegments", out var folderVal) && folderVal is not null)
                    {
                        if (folderVal is not List<object?> folderList)
                            return false;

                        foreach (var seg in folderList)
                        {
                            if (seg is not string segStr)
                                return false;
                            folderSegments.Add(segStr);
                        }
                    }

                    var node = root;
                    node = node.GetOrAddChild(group);
                    foreach (var segment in folderSegments)
                    {
                        node = node.GetOrAddChild(segment);
                    }

                    node.Leaves.Add(memberName);
                }
            }
            catch (FormatException)
            {
                return false;
            }

            source = Emit(root);
            return true;
        }

        private static string Emit(TrieNode root)
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated/> — CodeScenes Asset catalog. Do not edit.\n");
            sb.Append("public static class Assets\n{\n");
            EmitNode(sb, root, 1);
            sb.Append("}\n");
            return sb.ToString();
        }

        private static void EmitNode(StringBuilder sb, TrieNode node, int depth)
        {
            var indent = new string(' ', depth * 4);

            var childNames = new List<string>(node.Children.Keys);
            childNames.Sort(StringComparer.Ordinal);
            foreach (var childName in childNames)
            {
                sb.Append(indent).Append("public static class ").Append(childName).Append("\n");
                sb.Append(indent).Append("{\n");
                EmitNode(sb, node.Children[childName], depth + 1);
                sb.Append(indent).Append("}\n");
            }

            var leaves = new List<string>(node.Leaves);
            leaves.Sort(StringComparer.Ordinal);
            foreach (var leaf in leaves)
            {
                sb.Append(indent).Append("public static global::SceneBuilder.Authoring.AssetReference ")
                    .Append(leaf).Append(" => default!;\n");
            }
        }

        private sealed class TrieNode
        {
            public Dictionary<string, TrieNode> Children { get; } = new(StringComparer.Ordinal);
            public List<string> Leaves { get; } = new();

            public TrieNode GetOrAddChild(string name)
            {
                if (!Children.TryGetValue(name, out var child))
                {
                    child = new TrieNode();
                    Children[name] = child;
                }

                return child;
            }
        }
    }
}
