using System;
using System.Collections.Generic;
using System.Text;

namespace CodeScenes.Analyzers
{
    /// <summary>
    /// b3-t1: manifest JSON (Prefabs.sbfacade.json / FacadeCatalog shape) -> façade source (a
    /// `Prefabs` static class + one per-prefab namespace of ref types deriving from
    /// SceneBuilder.Authoring.PrefabRef). See
    /// .agent_handoffs/typed-prefab-facades/b3-t1/research.md "Blueprint" for the full contract.
    /// </summary>
    internal static class FacadeEmit
    {
        public static bool TryEmitFacades(string? json, out string source)
        {
            source = "";

            if (string.IsNullOrWhiteSpace(json))
                return false;

            List<ParsedEntry> entries;
            try
            {
                var root = CatalogEmit.MiniJson.Parse(json!);
                if (root is not Dictionary<string, object?> obj)
                    return false;

                if (!obj.TryGetValue("entries", out var entriesVal) || entriesVal is not List<object?> entriesList)
                    return false;

                if (entriesList.Count == 0)
                    return false;

                entries = new List<ParsedEntry>(entriesList.Count);
                foreach (var e in entriesList)
                {
                    if (e is not Dictionary<string, object?> entryObj)
                        return false;
                    if (!entryObj.TryGetValue("propertyName", out var pnVal) || pnVal is not string propertyName)
                        return false;
                    if (!entryObj.TryGetValue("root", out var rootVal) || rootVal is not Dictionary<string, object?> rootObj)
                        return false;

                    if (!TryParseNode(rootObj, out var rootNode))
                        return false;

                    entries.Add(new ParsedEntry(propertyName, rootNode));
                }
            }
            catch (FormatException)
            {
                return false;
            }

            source = Emit(entries);
            return true;
        }

        private static bool TryParseNode(Dictionary<string, object?> nodeObj, out ParsedNode node)
        {
            node = null!;

            if (!nodeObj.TryGetValue("typeName", out var tnVal) || tnVal is not string typeName)
                return false;

            var children = new List<ParsedChild>();
            if (nodeObj.TryGetValue("children", out var childrenVal) && childrenVal is not null)
            {
                if (childrenVal is not List<object?> childrenList)
                    return false;

                foreach (var c in childrenList)
                {
                    if (c is not Dictionary<string, object?> childObj)
                        return false;
                    if (!childObj.TryGetValue("propertyName", out var cpnVal) || cpnVal is not string childPropertyName)
                        return false;
                    if (!childObj.TryGetValue("node", out var cnVal) || cnVal is not Dictionary<string, object?> childNodeObj)
                        return false;

                    if (!TryParseNode(childNodeObj, out var childNode))
                        return false;

                    children.Add(new ParsedChild(childPropertyName, childNode));
                }
            }

            node = new ParsedNode(typeName, children);
            return true;
        }

        private static string Emit(List<ParsedEntry> entries)
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated/> — CodeScenes Prefab façade catalog. Do not edit.\n");
            sb.Append("public static class Prefabs\n{\n");
            foreach (var entry in entries)
            {
                sb.Append("    public static global::CodeScenes.Facades.").Append(entry.PropertyName)
                    .Append('.').Append(entry.Root.TypeName)
                    .Append(' ').Append(entry.PropertyName).Append(" => default!;\n");
            }

            sb.Append("}\n");

            foreach (var entry in entries)
            {
                sb.Append("namespace CodeScenes.Facades.").Append(entry.PropertyName).Append("\n{\n");

                var seen = new HashSet<string>(StringComparer.Ordinal);
                var uniqueNodes = new List<ParsedNode>();
                CollectUnique(entry.Root, seen, uniqueNodes);

                foreach (var node in uniqueNodes)
                {
                    sb.Append("    public class ").Append(node.TypeName)
                        .Append(" : global::SceneBuilder.Authoring.PrefabRef\n    {\n");
                    foreach (var child in node.Children)
                    {
                        sb.Append("        public ").Append(child.Node.TypeName)
                            .Append(' ').Append(child.PropertyName).Append(" => default!;\n");
                    }

                    sb.Append("    }\n");
                }

                sb.Append("}\n");
            }

            return sb.ToString();
        }

        private static void CollectUnique(ParsedNode node, HashSet<string> seen, List<ParsedNode> uniqueNodes)
        {
            if (seen.Add(node.TypeName))
                uniqueNodes.Add(node);

            foreach (var child in node.Children)
            {
                CollectUnique(child.Node, seen, uniqueNodes);
            }
        }

        private sealed class ParsedEntry
        {
            public ParsedEntry(string propertyName, ParsedNode root)
            {
                PropertyName = propertyName;
                Root = root;
            }

            public string PropertyName { get; }
            public ParsedNode Root { get; }
        }

        private sealed class ParsedNode
        {
            public ParsedNode(string typeName, List<ParsedChild> children)
            {
                TypeName = typeName;
                Children = children;
            }

            public string TypeName { get; }
            public List<ParsedChild> Children { get; }
        }

        private sealed class ParsedChild
        {
            public ParsedChild(string propertyName, ParsedNode node)
            {
                PropertyName = propertyName;
                Node = node;
            }

            public string PropertyName { get; }
            public ParsedNode Node { get; }
        }
    }
}
