#nullable enable
using System;
using System.Collections.Generic;
using System.Text;
using SceneBuilder.Core.Model;

namespace SceneBuilder.Editor
{
    /// <summary>
    /// b7-t2 (iteration 2): compiles the CURRENT on-disk <see cref="AssetCatalog"/> into a
    /// compilable stub of the generator-emitted <c>Assets</c> static class, so
    /// <see cref="BuilderCompileCheck"/> can honestly resolve <c>Assets.*</c> typed references
    /// without ever seeing the real <c>CodeScenes.Analyzers</c> source generator (which only runs
    /// in the real project csproj, never in this editor AppDomain). Structurally mirrors
    /// <c>CodeScenes.Analyzers/AssetCatalogEmit.cs</c>'s folder-tree merge (kept in lockstep by
    /// design — the two cannot share code across the analyzer boundary), but is POCO-driven off
    /// the same <see cref="AssetCatalog"/> shape emit already reads.
    /// </summary>
    internal static class AssetCatalogStubEmitter
    {
        /// <summary>
        /// Emits a compilable <c>public static class Assets { ... }</c> compilation unit: one
        /// nested class per <see cref="AssetCatalogEntry.Group"/> then per
        /// <see cref="AssetCatalogEntry.FolderSegments"/> segment (siblings share folder classes),
        /// folders in Ordinal order, and one
        /// <c>public static SceneBuilder.Authoring.AssetReference &lt;MemberName&gt; =&gt; default!;</c>
        /// per entry at its leaf. A member absent from <paramref name="catalog"/> is genuinely
        /// absent from the stub — so a stale typed reference is still a real, located compile
        /// error; the stub is honest by construction, never a blanket suppression.
        /// </summary>
        public static string Emit(AssetCatalog catalog)
        {
            var root = new TrieNode();

            foreach (var entry in catalog.Entries)
            {
                var node = root.GetOrAddChild(entry.Group);
                foreach (var segment in entry.FolderSegments)
                {
                    node = node.GetOrAddChild(segment);
                }

                node.Leaves.Add(entry.MemberName);
            }

            var sb = new StringBuilder();
            sb.Append("// <auto-generated/> — BuilderCompileCheck's in-memory Assets stub. Do not edit.\n");
            sb.Append("using SceneBuilder.Authoring;\n");
            sb.Append("public static class Assets\n{\n");
            EmitNode(sb, root, 1);
            sb.Append("}\n");
            return sb.ToString();
        }

        private static void EmitNode(StringBuilder sb, TrieNode node, int depth)
        {
            var indent = new string(' ', depth * 4);

            var childNames = new List<string>(node.Children.Keys);
            childNames.Sort(StringComparer.Ordinal);
            foreach (var childName in childNames)
            {
                sb.Append(indent).Append("public static class ").Append(childName).Append("\n");
                sb.Append(indent).Append("{\n");
                EmitNode(sb, node.Children[childName], depth + 1);
                sb.Append(indent).Append("}\n");
            }

            var leaves = new List<string>(node.Leaves);
            leaves.Sort(StringComparer.Ordinal);
            foreach (var leaf in leaves)
            {
                sb.Append(indent).Append("public static AssetReference ").Append(leaf).Append(" => default!;\n");
            }
        }

        private sealed class TrieNode
        {
            public Dictionary<string, TrieNode> Children { get; } = new(StringComparer.Ordinal);
            public List<string> Leaves { get; } = new();

            public TrieNode GetOrAddChild(string name)
            {
                if (!Children.TryGetValue(name, out var child))
                {
                    child = new TrieNode();
                    Children[name] = child;
                }

                return child;
            }
        }
    }
}
