#nullable enable
using System;
using System.Collections.Generic;
using System.Text;
using SceneBuilder.Core.Model;

namespace SceneBuilder.Editor
{
    /// <summary>
    /// b5-t1 (specs/30-live-verify-bug-fixes.md, Bug 5): compiles the CURRENT on-disk
    /// <see cref="FacadeCatalog"/> into a compilable stub of the generator-emitted
    /// <c>Prefabs</c> static class, so <see cref="BuilderCompileCheck"/> can honestly resolve
    /// <c>Prefabs.*</c> typed references without ever seeing the real
    /// <c>CodeScenes.Analyzers</c> source generator (which only runs in the real project csproj,
    /// never in this editor AppDomain). Structurally mirrors
    /// <c>CodeScenes.Analyzers/FacadeEmit.cs</c>'s node-graph emission (kept in lockstep by
    /// design — the two cannot share code across the analyzer boundary), but is POCO-driven off
    /// the same <see cref="FacadeCatalog"/> shape emit already reads. Sibling to
    /// <see cref="AssetCatalogStubEmitter"/>, whose honest-by-omission pattern it follows exactly.
    /// </summary>
    internal static class PrefabFacadeStubEmitter
    {
        /// <summary>
        /// Emits a compilable compilation unit reproducing FacadeEmit.Emit's shape: a
        /// <c>public static class Prefabs { ... }</c> with one
        /// <c>public static global::CodeScenes.Facades.&lt;PropertyName&gt;.&lt;Root.TypeName&gt; &lt;PropertyName&gt; =&gt; default!;</c>
        /// per <see cref="FacadeCatalog.Entries"/> entry, plus per entry a
        /// <c>namespace CodeScenes.Facades.&lt;PropertyName&gt;</c> containing one
        /// <c>public class &lt;Node.TypeName&gt; : global::SceneBuilder.Authoring.PrefabRef { ... }</c>
        /// per UNIQUE node (dedup by TypeName, first-seen order) reachable from the entry's Root.
        /// A member absent from <paramref name="catalog"/> is genuinely absent from the stub — so a
        /// stale typed reference is still a real, located compile error; the stub is honest by
        /// construction, never a blanket suppression.
        /// </summary>
        public static string Emit(FacadeCatalog catalog)
        {
            var sb = new StringBuilder();
            sb.Append("// <auto-generated/> — BuilderCompileCheck's in-memory Prefabs stub. Do not edit.\n");
            sb.Append("public static class Prefabs\n{\n");
            foreach (var entry in catalog.Entries)
            {
                sb.Append("    public static global::CodeScenes.Facades.").Append(entry.PropertyName)
                    .Append('.').Append(entry.Root.TypeName)
                    .Append(' ').Append(entry.PropertyName).Append(" => default!;\n");
            }

            sb.Append("}\n");

            foreach (var entry in catalog.Entries)
            {
                sb.Append("namespace CodeScenes.Facades.").Append(entry.PropertyName).Append("\n{\n");

                var seen = new HashSet<string>(StringComparer.Ordinal);
                var uniqueNodes = new List<FacadeNode>();
                CollectUnique(entry.Root, seen, uniqueNodes);

                foreach (var node in uniqueNodes)
                {
                    sb.Append("    public class ").Append(node.TypeName)
                        .Append(" : global::SceneBuilder.Authoring.PrefabRef\n    {\n");
                    foreach (var child in node.Children)
                    {
                        sb.Append("        public ").Append(child.Node.TypeName)
                            .Append(' ').Append(child.PropertyName).Append(" => default!;\n");
                    }

                    sb.Append("    }\n");
                }

                sb.Append("}\n");
            }

            return sb.ToString();
        }

        private static void CollectUnique(FacadeNode node, HashSet<string> seen, List<FacadeNode> uniqueNodes)
        {
            if (seen.Add(node.TypeName))
            {
                uniqueNodes.Add(node);
            }

            foreach (var child in node.Children)
            {
                CollectUnique(child.Node, seen, uniqueNodes);
            }
        }
    }
}
